name: flutter_inapp_inspector
description: A debugging mini app that provides insights into app performance, requests and logs.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.6.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2
  iconsax_flutter: ^1.0.0
  flutter_bloc: ^9.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true